name: SandRollbackPlugin
version: '${version}'
main: tree.sandrollback.SandRollbackPlugin
api-version: '1.20'
folia-supported: true
commands:
  SandRollbackReload:
    description: Reloads the sand rollback plugin 
